name: "Release"

on:
  push:
    tags:
      - '*'

permissions: {}

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Extract release notes
        run: |
          TAG_NAME="${GITHUB_REF##*/}"
          python3 <<EOF
          import re
          version = "${TAG_NAME}"
          with open('RELEASENOTES.md', 'r') as f:
              lines = f.readlines()
          pattern = re.compile(r'^##\s+' + re.escape(version) + r'\s*$')
          notes = []
          in_section = False
          for line in lines:
              if pattern.match(line):
                  in_section = True
                  continue
              if in_section and line.startswith('## '):
                  break
              if in_section:
                  notes.append(line.rstrip())
          with open('release_notes.txt', 'w') as out:
              out.write('\n'.join(notes).strip())
          EOF

      - name: ZIP the integration directory
        run: |
          cd custom_components/experimental
          zip -r ../../experimental.zip ./

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body_path: release_notes.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: experimental.zip
          asset_name: experimental.zip
          asset_content_type: application/zip
